name: Run tests
on:
  push:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
    test:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python: ['3.8', '3.9', '3.10', '3.11', '3.12']
      steps:
        - uses: actions/checkout@v4
        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python }}
        - name: Setup System Dependencies
          run: |
            sudo apt update
            sudo apt install libkrb5-dev -y
        - name: Install Tox and any other packages
          run: pip install tox
        - name: Run Tox
          # Run tox using the version of Python in `PATH`
          run: tox -epy
    flake8:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: 3.11
        - name: Setup System Dependencies
          run: |
            sudo apt update
            sudo apt install libkrb5-dev -y
        - name: Install Tox and any other packages
          run: pip install tox
        - name: Lint with flake8
          run: tox -eflake8
    twine:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: 3.11
        - name: Setup System Dependencies
          run: |
            sudo apt update
            sudo apt install libkrb5-dev -y
        - name: Install Tox and any other packages
          run: pip install tox
        - name: Run twine-check
          run: tox -etwine
